sudo: false
language: ruby
env:
  global:
    - CC_TEST_REPORTER_ID=18aab811b8decd95390672fc6eec558036fe67eddc166878ae660e356219f3f8
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
before_install:
  - gem install bundler
  - gem update --system
  - gem --version
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
